/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DealsIndexRouteImport } from './routes/deals.index'
import { Route as DealsNewRouteImport } from './routes/deals.new'
import { Route as DealsIdRouteImport } from './routes/deals.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIndexRoute = DealsIndexRouteImport.update({
  id: '/deals/',
  path: '/deals/',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsNewRoute = DealsNewRouteImport.update({
  id: '/deals/new',
  path: '/deals/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsIdRoute = DealsIdRouteImport.update({
  id: '/deals/$id',
  path: '/deals/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/deals/$id': typeof DealsIdRoute
  '/deals/new': typeof DealsNewRoute
  '/deals/': typeof DealsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/deals/$id': typeof DealsIdRoute
  '/deals/new': typeof DealsNewRoute
  '/deals': typeof DealsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/deals/$id': typeof DealsIdRoute
  '/deals/new': typeof DealsNewRoute
  '/deals/': typeof DealsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/deals/$id'
    | '/deals/new'
    | '/deals/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/dashboard' | '/deals/$id' | '/deals/new' | '/deals'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/deals/$id'
    | '/deals/new'
    | '/deals/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DealsIdRoute: typeof DealsIdRoute
  DealsNewRoute: typeof DealsNewRoute
  DealsIndexRoute: typeof DealsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/': {
      id: '/deals/'
      path: '/deals'
      fullPath: '/deals/'
      preLoaderRoute: typeof DealsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/new': {
      id: '/deals/new'
      path: '/deals/new'
      fullPath: '/deals/new'
      preLoaderRoute: typeof DealsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals/$id': {
      id: '/deals/$id'
      path: '/deals/$id'
      fullPath: '/deals/$id'
      preLoaderRoute: typeof DealsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DealsIdRoute: DealsIdRoute,
  DealsNewRoute: DealsNewRoute,
  DealsIndexRoute: DealsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
